config/routes.rb
Motherlode::Application.routes.draw do
  resources :home
  resources :nuggets
  resources :categories
  resources :users
  resources :sessions, only: [:create, :destroy, :new]
  get 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  root 'home#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :nuggets
  include ActsAsTree

  acts_as_tree order: 'name'

  def published_nuggets
    Nugget.where(category_id: id, published: true)
  end

  def unpublished_nuggets
    Nugget.where(category_id: id, published: false)
  end

  def all_nuggets
    Nugget.where(category_id: id)
  end
end

app/models/nugget.rb
class Nugget < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :nuggets
  has_secure_password
  validates_presence_of :password, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_product
    product = Category.where(parent_id: nil).first
    @current_product = product || Category.new({name: 'Product Undefined'})
  end

  def current_products
    products = Category.where(parent_id: nil)
    @current_products = products || Category.new({name: 'No Products Defined'})
  end

  helper_method :current_user, :current_product, :current_products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /
  def product_root
    @category = current_product
    @categories = current_products
    render action: 'show'
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"

  def index
    @products = current_products
  end

end

app/controllers/nuggets_controller.rb
class NuggetsController < ApplicationController
  before_action :set_nugget, only: [:show, :edit, :update, :destroy]

  # GET /nuggets
  # GET /nuggets.json
  def index
    @nuggets = Nugget.all
  end

  # GET /nuggets/1
  # GET /nuggets/1.json
  def show
  end

  # GET /nuggets/new
  def new
    @nugget = Nugget.new
  end

  # GET /nuggets/1/edit
  def edit
  end

  # POST /nuggets
  # POST /nuggets.json
  def create
    @nugget = Nugget.new(nugget_params)
    @nugget.published = false
    @nugget.user = current_user

    respond_to do |format|
      if @nugget.save
        format.html { redirect_to @nugget, notice: 'Nugget was successfully created.' }
        format.json { render action: 'show', status: :created, location: @nugget }
      else
        format.html { render action: 'new' }
        format.json { render json: @nugget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nuggets/1
  # PATCH/PUT /nuggets/1.json
  def update
    respond_to do |format|
      if @nugget.update(nugget_params)
        format.html { redirect_to @nugget, notice: 'Nugget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nugget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nuggets/1
  # DELETE /nuggets/1.json
  def destroy
    @nugget.destroy
    respond_to do |format|
      format.html { redirect_to nuggets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nugget
      @nugget = Nugget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nugget_params
      params.require(:nugget).permit(:title, :body, :user_id, :category_id, :published, :address, :latitude, :longitude)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Signed up!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :name, :email, :bio, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nuggets_helper.rb
module NuggetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { :role => "form" }) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Parent Category" %><br>
    <%= f.collection_select :parent_id, Category.all, :id, :name, :include_blank => true, class: "form-control" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="col-md-12 down-20px">
    <div class="panel panel-primary">
      <div class="panel-heading"
        <h4>Edit Category</h4>
      </div>

      <div class="panel-body">
        <%= render 'form' %>
      </div>

      <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Save Category</button>
        <%= link_to 'Back', categories_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('button[type="submit"]').click(function() {
      console.log("Category edit submit called...");
      $('form').submit();
    })
  })
</script>

app/views/categories/index.html.erb
<div class="container down-20px">
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4>Available Categories</h4>
      </div>

      <div class="panel-body">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Parent ID</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.description %></td>
                <td><%= category.parent.name unless category.parent.nil? %></td>
                <td class="action_column">
                  <%= link_to 'Show', category, class: "btn btn-default" %>
                  <%= link_to 'Edit', edit_category_path(category), class: "btn btn-default" %>
                  <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
                </td>
              </tr>
            <% end %>
          </tbody>

          <tfoot>
            <tr>
              <th colspan="4">
                <% if @categories.count == 0 %>
                  There are 0 categories in the system.  Click the "New Category" button to create one!
                <% elsif @categories.count == 1 %>
                  There is 1 category in the system.
                <% else %>
                  There are <%= @categories.count %> categories in the system
                <% end %>
              </th>
            </tr>
          </tfoot>
        </table>
      </div>

      <div class="panel-footer">
        <%= link_to 'New Category', new_category_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container down-20px">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>New category</h4>
      </div>

      <div class="panel-body">
        <%= render 'form' %>
      </div>

      <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Save Category</button>
        <%= link_to 'Back', categories_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('button[type="submit"]').click(function() {
      console.log("Category new submit called...");
      $('form').submit();
    })
  })
</script>

app/views/categories/show.html.erb
<div class="container down-20px">
  <div class="col-md-12">
    <% unless @category.parent.nil? %>
    <ol class="breadcrumb">
      <% @category.ancestors.reverse.each do |category| %>
          <li><%= link_to category.name, category %></li>
      <% end %>
      <li class="current">
        <%= link_to @category.name, @category %>
      </li>
    </ol>
    <% end %>
  </div>

  <div class="col-md-12">
    <% unless @category.parent.nil? %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4><%= @category.name %></h4>
          </div>

          <div class="panel-body">
            <div class="row">
              <div class="col-lg-8">
                <%= render "categories/show/details" %>
                <%= render "categories/show/nuggets" %>
              </div>

              <div class="col-lg-4">
                <%= render "categories/show/subcategories" %>
              </div>
            </div>
          </div>

          <div class="panel-footer">
            <%= link_to 'Add Nugget', new_nugget_path, class: "btn btn-primary" %>
            <%= link_to 'Back', :back, class: "btn btn-default" %>
          </div>
        </div>
    <% else %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Motherlode Products</h4>
        </div>
        <ul class="list-group">

        </ul>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Categories for <%= @category.name %></div>
        <ul class="list-group">
          <% @category.children.each do |child_category| %>
            <li class="list-group-item">
              <%= link_to child_category.name, child_category %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show/_details.html.erb
<p><%= @category.description %></p>
<% if current_user && current_user.admin %>
  <%= link_to 'Edit Category', edit_category_path(@category) %> |
<% end %>

<% if current_user && current_user.admin? && @category.unpublished_nuggets.count > 0  # || current_user.moderator? @category %>
  <div class="panel panel-default">
    Pending content
    <ul>
      <% @category.unpublished_nuggets.each do |nugget| %>
        <li><%= link_to nugget.title, nugget %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/categories/show/_nuggets.html.erb
<% @category.self_and_children.each do |category| %>
  <ul>
    <% category.published_nuggets.each do |nugget| %>
      <li><h4><%= link_to nugget.title, nugget %> (<%= nugget.user.name %>)</h4></li>
    <% end %>
  </ul>
<% end %>

app/views/categories/show/_subcategories.html.erb
<% if @category.children.count > 0 %>
  <div class="panel panel-default">
    <div class="panel-heading"><%= @category.name %> Sub Categories</div>
    <ul class="list-group">
      <% @category.children.each do |child_category| %>
        <li class="list-group-item">
          <%= link_to child_category.name, child_category %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="col-md-4">
      <h1>Explore</h1>
      <p>&nbsp;</p>
      <p class="cols-md-5">
        <%= select "product", "id", @products.map {|u| [u.name, u.id]}, {:include_blank => 'Select a product...'}, class: "form-control" %>
      </p>
    </div>
    <div class="col-md-4 col-md-offset-2">
      <h1>Contribute</h1>
      <p>&nbsp;</p>
      <p class="center-block">
        <a class="btn btn-info btn-lg" role="button">Learn more &raquo;</a>
        <a class="btn btn-primary btn-lg" role="button">Signup!</a>
      </p>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('product').change(function() {
      console.log("product changed...");
    })
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motherlode</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body class="down-50px">
  <%= render "partials/sitenav" %>
  <%= render "partials/alert" %>
  <%= yield %>
  <script type="text/javascript">
      $(document).ready( function() {
          $("#nugget_address").change( function() {
              if(this.value != '')
                  codeAddress(this.value);
          });
      });
  </script>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home | Motherlode</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body class="down-50px">

  <%= render "partials/sitenav" %>

  <%= render "partials/alert" %>

  <%= yield %>

</body>
</html>

app/views/nuggets/_form.html.erb
<%= form_for(@nugget, html: { role: "form" }) do |f| %>
  <% if @nugget.errors.any? %>
    <div class="alert alert-danger panel-padding" id="error_explanation">
      <h2><%= pluralize(@nugget.errors.count, "error") %> prohibited this nugget from being saved:</h2>
      <ul>
      <% @nugget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-9 panel-column-border-right">
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :body %><br>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :address %><br>
        <%= f.text_area :address, :class => "form-control" %>
      </div>
      <div class="form-group">
        <div class="form-inline">
          <%= f.label :latitude %><br>
          <%= f.text_field :latitude, :class => "form-control" %>

          <%= f.label :longitude %><br>
          <%= f.text_field :longitude, :class => "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-lg-3">
      <div class="form-group">
        <%= f.label :author_id %><br>
        <%= f.collection_select :user_id, User.all, :id, :name, { :class => "form-control" } %>
      </div>
      <div class="form-group">
        <%= f.label :category %><br>
        <%= f.collection_select :category_id, Category.all, :id, :name, :include_blank => true, class: "form-control" %>
      </div>
      <label class="checkbox-inline">
        <%= f.check_box :published %>
        Published
      </label>
    </div>
  </div>
<% end %>

app/views/nuggets/_new.html.erb
<%= form_for(@nugget, html: { :role => "form" }) do |f| %>
  <% if @nugget.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(@nugget.errors.count, "error") %> prohibited this nugget from being saved:</h2>
      <ul>
        <% @nugget.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-8 panel-column-border-right">
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_area :address, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :latitude %><br>
      <%= f.text_field :latitude, :class => "form-control" %>

      <%= f.label :longitude %><br>
      <%= f.text_field :longitude, :class => "form-control" %>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="form-group">
      <%= f.label :category %><br>
      <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control" %>
    </div>
  </div>
<% end %>

app/views/nuggets/edit.html.erb
<div class="container down-20px">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>Edit Nugget</h4>
    </div>

    <div class="panel-body">
      <%= render 'form' %>
    </div>

    <div class="panel-footer">
      <button type="submit" class="btn btn-primary">Save Nugget</button>
      <%= link_to 'Back', nuggets_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('button[type="submit"]').click(function() {
      console.log("Nugget edit submit called...");
      $('form').submit();
    })
  })
</script>

app/views/nuggets/index.html.erb
<div class="container down-20px">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h4>Available Nuggets</h4>
    </div>

    <div class="panel-body">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Category</th>
            <th>Published</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @nuggets.each do |nugget| %>
            <tr>
              <td><%= nugget.title %></td>
              <td><%= nugget.user.name if nugget.user%></td>
              <td>
                <% if nugget.category nil? %>
                  <%= nugget.category.name %>
                <% else %>
                  &nbsp;
                <% end %>
              </td>
              <td><%= nugget.published %></td>
              <td class="action_column">
                <%= link_to 'Show', nugget, class: "btn btn-default" %>
                <%= link_to 'Edit', edit_nugget_path(nugget), class: "btn btn-default" %>
                <%= link_to 'Destroy', nugget, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
              </td>
            </tr>
          <% end %>
        </tbody>

        <tfoot>
          <tr>
            <th colspan="6">
              <% if @nuggets.count == 0 %>
                There are no nuggets in the system, click the "New Nugget" button to add one!
              <% elsif @nuggets.count == 1 %>
                There is 1 nugget in the system
              <% else %>
                There are <%= @nuggets.count %> nuggets in the system
              <% end %>
            </th>
          </tr>
        </tfoot>
      </table>
    </div>

    <div class="panel-footer">
      <%= link_to 'New Nugget', new_nugget_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/nuggets/new.html.erb
<div class="container down-20px">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>New Nugget</h4>
    </div>

    <div class="panel-body">
      <%= render 'new' %>
    </div>

    <div class="panel-footer">
      <button type="submit" class="btn btn-primary">Save Nugget</button>
      <%= link_to 'Back', nuggets_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('button[type="submit"]').click(function() {
      console.log("Nugget new submit called...");
      $('form').submit();
    })
  })
</script>

app/views/nuggets/show.html.erb
<div class="container down-20px">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><%= @nugget.title %></h4>
    </div>

    <div class="panel-body">
      <p id="notice"><%= notice %></p>
      <% unless @nugget.published %>
        <div class="alert">
          PENDING MODERATION
        </div>
      <% end %>

      <% if @nugget.user %>
        <h5>by <%= @nugget.user.name %></h5>
      <% end %>

      <%= @nugget.body %>

      <% if @nugget.category nil? %>
        <p>
          <strong>Category:</strong>
          <%= @nugget.category.name %>
        </p>
      <% end %>
    </div>

    <div class="panel-footer">
      <%= link_to 'Back', nuggets_path, class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_nugget_path(@nugget), class: "btn btn-default" %>
    </div>
  </div>
</div>

app/views/partials/_alert.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
    <% if notice %>
      <div class="alert alert-info">
      <%= notice %>
        <a href="#" class="close">&times;</a>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_sitenav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Motherlode</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/categories">Categories</a></li>
        <li><a href="/nuggets">Nuggets</a></li>
        <li><a href="/users">Users</a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li>
          <% if current_user %>
            Welcome back, <%= current_user.username %><br />
            <%= link_to 'My Account', current_user %> |
            <% if current_user && current_user.admin %>
              <%= link_to 'Administer Products', users_path %> |
              <%= link_to 'Manage Users', users_path %> |
            <% end %>
            <%= link_to 'Sign Out', :logout%>
          <% else %>
            <%= link_to 'Sign In', :login %>
          <% end %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/users/edit.html.erb
<div class="container down-20px">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>Edit User</h4>
    </div>

    <div class="panel-body">
      <%= render 'edit' %>
    </div>

    <div class="panel-footer">
      <button type="submit" class="btn btn-primary">Save User</button>
      <%= link_to 'Back', users_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('button[type="submit"]').click(function() {
      console.log("User edit submit called...");
      $('form').submit();
    })
  })
</script>

app/views/users/index.html.erb
<div class="container down-20px">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h4>Manage Users</h4>
    </div>

    <div class="panel-body">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Username</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><% if user.admin %> Administrator <% else %> Contributor <% end %></td>
              <td class="action_column">
                <%= link_to 'Show', user, class: "btn btn-default" %>
                <%= link_to 'Edit', edit_user_path(user), class: "btn btn-default"%>
                <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
              </td>
            </tr>
          <% end %>
        </tbody>

        <tfoot>
          <tr>
            <th colspan="5">
              <% if @users.count == 0 %>
                There are no users in the system. Click the "New User" button to add one!
              <% elsif @users.count == 1 %>
                There is 1 user in the system.
              <% else %>
                There are <%= @users.count %> users in the system
              <% end %>
            </th>
          </tr>
        </tfoot>
      </table>
    </div>

    <div class="panel-footer">
      <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container down-20px">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>Create User</h4>
    </div>

    <div class="panel-body">
      <%= render 'edit' %>
    </div>

    <div class="panel-footer">
      <button class="btn btn-primary" type="submit">Save User</button>
      <%= link_to 'Back', users_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('button[type="submit"]').click(function() {
      console.log("User new submit called...");
      $('form').submit();
    })
  })
</script>

app/views/users/show.html.erb
<div class="container down-20px">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4>User <%= @user.name %></h4>
    </div>

    <div class="panel-body">
      <p><a href="<%= @user.email %>"><%= @user.email %></a></p>
      <p><%= @user.bio %></p>

      <h4>Author of the following content...</h4>
      <ul>
        <% Nugget.where(user_id: @user.id).each do |nugget| %>
        <li><%= link_to nugget.title, nugget_path%></li>
        <% end %>
      </ul>
    </div>

    <div class="panel-footer">
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %>
      <%= link_to 'Back', users_path, class: "btn btn-default" %>
    </div>
  </div>
</div>